### ISSUE TITLE
Expose error info to downstream downloader middlewares upon Zyte API errors

### ISSUE THREAD

**Issue by starrify** [scrapy-plugins/scrapy-zyte-api#25]
..so that further processing may happen, like retries.

As of the current revision of a188fcc5, here's the respective code I'm referring to:

https://github.com/scrapy-plugins/scrapy-zyte-api/blob/a188fcc5de3bca1aee3a9e8c070ba62943ee83e8/scrapy_zyte_api/handler.py#L90-L95

Here's a sample piece of log that a job may have, as emitted by the above code's execution:
(in this very example the job used Smart Browser, and the error here indicated a ban that shall be retried from the user's end)

> [scrapy_zyte_api.handler] Got Zyte API error (520) while processing URL (<some-url-here>): There is a downloading problem which might be temporary. Retry in N seconds from 'Retry-After' header.

In such cases the spider may want to retry such requests, it may not easily do so due to the downloader handler's behavior (`raise IgnoreRequest()`).

Two possible approaches as I may think of are:
1. To unpack that `zyte_api.aio.errors.RequestError` exception into a `scrapy.http.Request` anyway and return it.
2. To raise an exception different than `scrapy.exceptions.IgnoreRequest` and include the error details. (maybe just raise the same `zyte_api.aio.errors.RequestError` already?)

IMHO approach 2 may be a better one.

**Comment by starrify** [comment]
Thanks @Gallaecio for the quick follow up!

Regarding the motivation, I think user-initiated retries may be a valid (and somehow common) use case for the SB (Smart Browser).

By default SB performs up to 3 internal retries upon bans (similar to Crawlera), and would returned a banned status to user after that. When the ban rate is not too high, it is expected behavior for the user to attempt a few (e.g. 3) retries when they receive occasional banned responses.

For example, here is the sample job I checked previously: [link](https://app.zyte.com/p/199949/17/135/log?filterAndHigher=true&filterType=error) (requires access to Scrapy Cloud). The sample job sent 2149 requests to Zyte API, out of which only 1 failed. This is the ideal scenario if we could just retry that request from within the spider.

A work-around, as I suggested to the spider's developer, was to also retry the `IgnoreRequest` exception (to add it to the built-in RetryMiddleware's configs, or to use a custom downloader middleware for the check). In this case a separate exception type and further info with the exception object may be very much helpful.

**Comment by Gallaecio** [comment]
It turns out for HTTP 520 the client is not retrying. I think that is a bug in the client, and https://github.com/zytedata/python-zyte-api/pull/17 should fix that.

**Comment by starrify** [comment]
Hi, a kind reminder here that we have received multiple reports from Deliver devs and support engineers that this issue affects their jobs.

Personally I shall be okay with either option: to have it retried within the zyte-api package (https://github.com/zytedata/python-zyte-api/pull/17) or to have it retried by Scrapy (just expose the error here other than `IgnoreRequest`).

**Comment by kmike** [comment]
I wonder why was IgnoreRequest used in a first place. It seems reasonable to raise another error.

**Comment by kmike** [comment]
The original title is "Expose error info to downstream downloader middlewares upon Zyte API errors", so +1 to keep the issue open, and look into switching from IgnoreRequest - we still don't expose error info to downstream middlewares.
